sudo: false
language: python
cache: pip
python:
  - "2.7"
  - "3.6"
  - "pypy"
addons:
  postgresql: "9.4"
services:
  - postgresql
# command to install dependencies
install:
  - pip install setuptools --upgrade
  - python setup.py develop
  - pip install nose coverage coveralls
  - 'if [[ "$TRAVIS_PYTHON_VERSION" != "pypy" ]]; then pip install psycopg2; fi'
# command to run tests
before_script:
  - psql -c 'create database myapp_test;' -U postgres
script:
  - 'if [[ "$TRAVIS_PYTHON_VERSION" != "pypy" ]]; then ./runtests.sh; fi'
  - 'if [[ "$TRAVIS_PYTHON_VERSION" == "pypy" ]]; then SQLALCHEMY_DATABASE_URI="sqlite://" ./runtests.sh ; fi'
after_success:
  - coveralls
notifications:
  email: false
  slack:
    - hasgeek:HDCoMDj3T4ICB59qFFVorCG8
    - friendsofhasgeek:3bLViYSzhfaThJovFYCVD3fX
