language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
# command to install dependencies
install:
  - python setup.py develop
  - pip install -r test_requirements.txt . --use-mirrors
# command to run tests
before_script:
  - psql -c 'create database myapp_test;' -U postgres
  - echo -e 'from psycopg2ct import compat\ncompat.register()' > psycopg2.py
  - export PYTHONPATH=`pwd`:$PYTHONPATH
script: nosetests 
notifications:
  email: false
  irc: "irc.freenode.net#hasgeek-dev"
