sudo: false
language: python
cache: pip
python:
  - "2.7"
  - "pypy"
# command to install dependencies
install:
  - python setup.py develop
  - pip install nose coverage coveralls --use-mirrors
  - 'if [[ "$TRAVIS_PYTHON_VERSION" != "pypy" ]]; then pip install psycopg2 --use-mirrors; fi'
# command to run tests
before_script:
  - psql -c 'create database myapp_test;' -U postgres
script:
  - 'if [[ "$TRAVIS_PYTHON_VERSION" != "pypy" ]]; then coverage run `which nosetests`; fi'
  - 'if [[ "$TRAVIS_PYTHON_VERSION" == "pypy" ]]; then SQLALCHEMY_DATABASE_URI="sqlite://" coverage run `which nosetests` ; fi'
after_success:
  - coveralls
notifications:
  email: false
  slack: friendsofhasgeek:3bLViYSzhfaThJovFYCVD3fX
