sudo: false
language: python
cache: pip
python:
  - "2.7"
  - "3.6"
addons:
  postgresql: "9.4"
services:
  - postgresql
# command to install dependencies
install:
  - pip install setuptools --upgrade
  - python setup.py develop
  - pip install nose coverage coveralls psycopg2
  - 'if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then pip install PySqlite; fi'
# command to run tests
before_script:
  - psql -c 'create database myapp_test;' -U postgres
script:
  - ./runtests.sh
after_success:
  - coveralls
notifications:
  email: false
  slack:
    - hasgeek:HDCoMDj3T4ICB59qFFVorCG8
    - friendsofhasgeek:3bLViYSzhfaThJovFYCVD3fX
